apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "label-studio.fullname" . }}
  labels:
    {{- include "label-studio.labels" . | nindent 4 }}
data:
  email: {{ .Values.default_user.email | b64enc | quote }}
  password: {{ .Values.default_user.password | b64enc | quote }}
  token: {{ .Values.default_user.token | b64enc | quote }}
